### ISSUE TITLE
Side by side diff toggle makes code lines "double separated"

### ISSUE THREAD

**Issue by ldipenti** [ForkIssues/Tracker#1088] opened 2020-07-22 21:05 UTC
When enabling or disabling "side by side diff" view on the changes panel, the code start to look as separated by a double newline char (see attached screenshot).
This can be fixed by clicking on for example the "ignore whitespaces" button, but the issue re-appears when clicking the side by side view button again.

<img width="861" alt="image" src="https://user-images.githubusercontent.com/104905/88228477-9aca9980-cc45-11ea-8750-e28c64e553c3.png">

**Comment by DanPristupov** [comment] 2020-07-22 21:24
I can't reproduce this. Does the problem occur on a particular file?

**Comment by ldipenti** [comment] 2020-07-22 21:27
Seems to be happening only on .go files

**Comment by DanPristupov** [comment] 2020-08-23 14:54
> Seems to be happening only on .go files

Turned out `go` developers like tabs which caused the problem :).

The problem is fixed in 1.0.97

**Closed as completed** 2021-01-28 14:12 UTC
