### ISSUE TITLE
[FR] Please add feature to zoom in the commits window or source code

### ISSUE THREAD

**Issue by aceslick911** [ForkIssues/Tracker#1617] opened 2022-06-08 01:06 UTC
Feature Request:

I love to use Fork often for code reviews or demos - It would be very helpful to increase the size of the commit graph and the source code.

Is there any way to do this currently or can I please request this as a feature?

Would help with accessibility too for people with high res monitors and difficulty reading small text

**Comment by aceslick911** [comment] 2022-06-08 01:07
also to mention https://github.com/fork-dev/Tracker/issues/1178 - if this was CMD + or CMD - it would be very intuitive as most code IDES support this :)

**Comment by DanPristupov** [comment] 2022-06-08 06:26
The UI on macOS is not scalable.
As you said, that's a duplicate of #1178.

**Closed as completed** 2022-06-21 06:55 UTC
