### ISSUE TITLE
App Hangs when closing tabs

### ISSUE THREAD

**Issue by ghost** [ForkIssues/Tracker#536] opened 2019-02-20 14:55 UTC
**App version:**
v1.0.73.4 (using the built-in Git client, and not macOS built-in)

**App Integration:**
iTerm (For terminal)
Kaleidoscope (for Diffs)

**OS Version:** 
macOS Mojave 10.14.3

**Reproducing Steps (Tentative):**
- Open multiple Git Projects (or 1 project, with sub-modules. No pre/post commit hooks in my projects)
- Play with tabs over a period of time (opening, closing submodules, doing pull, fetch)

**Expected Behaviour:**
- Works fines

**Actual Behaviour (erratic):**
- When closing a tab, sometimes the app becomes unresponsive (spinning ball of death). 

**Workaround** 
Force kill the process, and start it again.

**Notes**
I'd say this behaviour happens a couple of times per day, I haven't identified a clear pattern of why / how it occurs. If I ever do, I will probably log it back it here.

**Comment by nebhale** [comment] 2019-02-21 14:46
I see the same but can’t reproduce it reliably enough to open a bug report about it.  My limited insight is that I see it if I’m rapidly closing tabs and maybe close a tab before its refresh-on-focus has completed I see it.  I think.

**Comment by DanPristupov** [comment] 2019-02-21 14:55
I have a suspicion... If it's right, this can be reproduced by activating a tab with a large repo and immediately closing it.

**Comment by nebhale** [comment] 2019-02-21 16:39
Large repo in terms of commits or files?

**Comment by DanPristupov** [comment] 2019-02-21 17:17
I meant the files.

I was probably wrong though. Fork **waits** for all activities before closing tab. I suspected that tab waits for all the repository background threads to finish, but it turned out that Fork cancels the threads and they get terminated almost immediately. Maybe some particular operations don't support cancelling 🤔...

There's internal benchmark in Fork which logs UI freezes. It might help us. When this happens next time, you can check the latest lines in the log file at `~/Library/Caches/Fork/fork.log` (or send it to support@forkapp.io).

Does this problem bother you a lot? I can create a build for you a release with additional logging.

**Comment by choule-spiria** [comment] 2019-02-21 18:21
The Repo itself is not all that big, but it does use Git-LFS for Binary Files, so this may be a variable.

Next time it occurs, I will pipe the content of the `fork.log` file here, and perhaps we'll have more clues as to why it spins.

Since I upgraded to 1.0.74.1, it has not occurred yet.

**Comment by choule-spiria** [comment] 2019-02-25 12:13
Here is the last 20 lines of the Fork.log with the error.

```
🔅[NSOperationQueue 0x6000000b06a0 (QOS: UNSPECIFIED)] [Stopwatch.swift:28] traceElapsedTime() > 14 GetRevisionsGitCommand
🔅[NSOperationQueue 0x6000000b06a0 (QOS: UNSPECIFIED)] [Stopwatch.swift:28] traceElapsedTime() > 374 RefreshRepositoryDataGitCommand
📢[NSOperationQueue 0x6000000b06a0 (QOS: UNSPECIFIED)] [RefreshRepositoryCommand.swift:221] refreshRepositoryData > Refresh 'core' data. Updated.
🔅[NSOperationQueue 0x6000000b06a0 (QOS: UNSPECIFIED)] [Stopwatch.swift:28] traceElapsedTime() > 69 GetRepositoryStateGitCommand
🔅[NSOperationQueue 0x6000000b06a0 (QOS: UNSPECIFIED)] [Stopwatch.swift:28] traceElapsedTime() > 141 GetRepositoryStatusGitCommand
📢[main] [RefreshRepositoryCommand.swift:176] refreshRepositoryStatus > Refresh 'core' status. Updated (0 files).
🔅[main] [JobQueue.swift:53] cancelAndWaitAllTasks() > Cancel and wait all jobs: 0
🔅[main] [JobQueue.swift:71] cancelAndWaitAllTasks() > Cancelled all jobs
🔅[main] [JobQueue.swift:53] cancelAndWaitAllTasks() > Cancel and wait all jobs: 0
🔅[main] [JobQueue.swift:71] cancelAndWaitAllTasks() > Cancelled all jobs
🔅[NSOperationQueue 0x6000000f00c0 (QOS: UNSPECIFIED)] [Stopwatch.swift:28] traceElapsedTime() > 37 GetRevisionsGitCommand
🔅[NSOperationQueue 0x6000000f00c0 (QOS: UNSPECIFIED)] [Stopwatch.swift:28] traceElapsedTime() > 405 RefreshRepositoryDataGitCommand
📢[NSOperationQueue 0x6000000f00c0 (QOS: UNSPECIFIED)] [RefreshRepositoryCommand.swift:221] refreshRepositoryData > Refresh 'kotlibs' data. Updated.
🔅[NSOperationQueue 0x6000000f00c0 (QOS: UNSPECIFIED)] [Stopwatch.swift:28] traceElapsedTime() > 69 GetRepositoryStateGitCommand
🔅[NSOperationQueue 0x6000000f00c0 (QOS: UNSPECIFIED)] [Stopwatch.swift:28] traceElapsedTime() > 148 GetRepositoryStatusGitCommand
📢[main] [RefreshRepositoryCommand.swift:176] refreshRepositoryStatus > Refresh 'kotlibs' status. Updated (0 files).
🔅[main] [JobQueue.swift:53] cancelAndWaitAllTasks() > Cancel and wait all jobs: 1
🔅[main] [JobQueue.swift:57] cancelAndWaitAllTasks() > Aborting 'Refreshing kotlibs'
🔅[main] [JobQueue.swift:66] cancelAndWaitAllTasks() > Waiting 'Refreshing kotlibs'.
```

Looks like it's waiting for a cancel, and the cancel never completes (or it completed so fast, it's a race?)

**Comment by choule-spiria** [comment] 2019-02-25 12:17
And I think I have a new details, I noticed that when I restart the app, I can reproduce it at while because the previous window state get restored after the kill. And the problems shows itself because I close the tabs using the keyboard in a quick succession.

So let's say I have 8 tabs with 8 different repo, and I start to spam the Command-W to close tabs, it close the current tab, focus the next one, which trigger a git fetch, and then I close it, it got to cancel the fetch, and it eventually spins on one of them.

If I do it using the mouse, I close tabs that are not in focus, then the problem does not present itself.

**Comment by DanPristupov** [comment] 2019-02-25 13:23
@choule-spiria I don't see anything wrong in the log. I will follow the reproduction steps. Thank you!

**Comment by DanPristupov** [comment] 2019-03-26 13:19
Hi guys!

I made few changes/improvements and created a develop build. On my side I don't see any freezes.

https://forkapp.ams3.cdn.digitaloceanspaces.com/mac/Fork-1.0.75.5.dmg (no need to install, you can run it from the dmg file)

Could you try to use it for some time and give me your feedback?

**Comment by nebhale** [comment] 2019-04-18 16:20
I've been using the snapshot for a week now and haven't seen any hangs.

**Comment by DanPristupov** [comment] 2019-04-18 16:27
However it seems to crash the application rarely. I'm trying to reproduce the problem right now. I may roll things back until I manage to fix it.

**Closed** 2020-06-17 15:29 UTC
