### ISSUE TITLE
keyboard shortcut H does not work on Reset Current Branch to Revision dialog

### ISSUE THREAD

**Issue by jimka2001** [ForkIssues/Tracker#1782] opened 2023-01-06 13:38 UTC
When I use the context menu to reset the current brach to a different commit in the revision history,
it (correctly) pops up a dialog asking what to do with the differences.
![Screenshot 2023-01-06 at 14 30 00](https://user-images.githubusercontent.com/6414129/211022564-83d6328f-e34d-4af4-9239-7555181c4804.png)
![Screenshot 2023-01-06 at 14 30 24](https://user-images.githubusercontent.com/6414129/211022597-956ee52f-1a64-4d8f-9890-a95fab964d47.png)

If I use the mouse to select **Hard**, and press **Reset**, it works correctly.
However, if I press the H key, then the menu item changes to: **Hard Discard All Local Changes**,
![Screenshot 2023-01-06 at 14 30 55](https://user-images.githubusercontent.com/6414129/211022728-4e63a1be-6878-4bfc-888b-6386e73fbe35.png)
But then when I press **Reset**, the branch is reset, but I have lots of changes added to the work area.
![Screenshot 2023-01-06 at 14 31 18](https://user-images.githubusercontent.com/6414129/211022811-6e565955-d401-41fc-8844-c653b78e9c47.png)
![Screenshot 2023-01-06 at 14 31 28](https://user-images.githubusercontent.com/6414129/211022829-5c115571-6571-4284-af4c-9f24bbb96a4c.png)

It would be great if pressing the H key did the same thing as selecting : **Hard Discard All Local Changes**

Here is the version information which might be helpful.

![Screenshot 2023-01-06 at 14 37 26](https://user-images.githubusercontent.com/6414129/211023215-25da93a4-3a0a-463c-a89f-8c2221e26166.png)

![Screenshot 2023-01-06 at 14 37 58](https://user-images.githubusercontent.com/6414129/211023314-fe5aafad-0009-4175-89ec-02f5d2bbb77c.png)

**Comment by DanPristupov** [comment] 2023-01-09 11:28
Most likely this happens when you use a non-English keyboard layout.

**Comment by jimka2001** [comment] 2023-01-09 14:42
I'm using a qwerty keyboard.  I'm not 100% sure whether it is British or US.  Would that matter?
![WhatsApp Image 2023-01-09 at 15 43 01](https://user-images.githubusercontent.com/6414129/211334777-35b21dd1-4dd5-48ad-8ec1-a6281edf2d91.jpeg)

**Comment by DanPristupov** [comment] 2023-01-09 14:45
I mean this one: 
<img width="550" alt="Screenshot 2023-01-09 at 15 44 40" src="https://user-images.githubusercontent.com/618115/211334965-354c8614-874a-402e-8bf9-2f6a59bdbbcd.png">

**Comment by jimka2001** [comment] 2023-01-09 15:02
I'm using this one.

![Screenshot 2023-01-09 at 16 01 54](https://user-images.githubusercontent.com/6414129/211339127-a24401dd-4cd2-4095-8287-1eeb99958624.png)

**Comment by DanPristupov** [comment] 2023-01-16 08:37
Hi. Could you check if the problem is fixed in Fork 2.25?

**Comment by jimka2001** [comment] 2023-01-16 18:03
Yes, it seems to work in Version 2.25.2

**Closed as completed** 2023-02-25 15:06 UTC
