### ISSUE TITLE
Merge LFS tracked files is not supported and results in corrupted LFS files

### ISSUE THREAD

**Issue by tofi86** [ForkIssues/Tracker#1031] opened 2020-05-25 16:14 UTC
I have a project where we track PDF files for comparison with Git LFS:

**.gitattributes**
```
*.pdf filter=lfs diff=lfs merge=lfs -text
```

Now I had the situation where some of the PDF files changed in both branches and when I merged the branches with Fork, I was presented with the known "Git Error" Dialog which lists all the merge conflicts:

```
Auto-merging test/2-sprachige-Ansicht/sd_smashdocs_expected.pdf
CONFLICT (content): Merge conflict in test/2-sprachige-Ansicht/sd_smashdocs_expected.pdf
```

<img width="405" alt="grafik" src="https://user-images.githubusercontent.com/365118/82829080-ba964900-9eb2-11ea-9660-d45e7a62a321.png">

I expected to be able to resolve the conflict by choosing either of the two LFS tracked files like I'm able to do with regular files.

But instead, when clicking on such a conflicting LFS file, Fork would say "File conflicts are resolved":

<img width="1002" alt="grafik" src="https://user-images.githubusercontent.com/365118/82829198-f16c5f00-9eb2-11ea-922a-bf681f452472.png">

The first time, I staged the file in confusion which resulted in the following content to be submitted as a new LFS revision for the PDF file:

```
version https://git-lfs.github.com/spec/v1
<<<<<<< HEAD
oid sha256:66ede0e4c5185d63feddacb43e8210ddff8d969e87bc369029647463ed4f6e7f
size 451730
=======
oid sha256:5f931b7d954566780f003279d93e8f7e9e5474027a317ec531622f315d89fe28
size 451444
>>>>>>> development
```

Fork really commits THIS content als the content of the PDF LFS file!

Also, in the current state of merging / conflict resolving, this is also visible when viewing the LFS tracked file for example in VS Code.

Though I found out, I CAN resolve the conflict correctly by choosing "Resolve using Mine/Theirs" from the right click context menu. But actually I would expect to see the "visual" conflict resolution screen as known for other file types.

Is there any chance to support this?

----

FYI: This also happens for the Windows Client!

**Comment by DanPristupov** [comment] 2020-05-26 10:04
I'm investigating this problem right now and I don't see a way to fix this quickly. Git considers LFS pointers as a text diff and sometimes automatically merges them (incorrectly).

Please try to update .gitattributes as a workaround. This prevents automatic text merge:

**.gitattributes**
```
*.pdf filter=lfs diff=lfs merge=lfs binary
```

**Comment by tofi86** [comment] 2020-05-26 10:19
Ah, okay. Thanks for the tip! I will definitely try that. I didn't even question the `-text` attribute because it was set by Fork when adding the LFS filter *and* because I thought it would *unset* the text attribute on the filetype and therefore don't merge in text mode...

**Comment by DanPristupov** [comment] 2020-05-26 10:50
> I didn't even question the -text attribute because it was set by Fork when adding the LFS filter

This is what `git lfs track` does.

I'd like to add some more info.

This is a strange problem between LFS and git. As you probably know, instead of storing a binary file, LFS stores it as a pointer in a text format. Git doesn't know about LFS and in some cases conflicts in LFS files can be wrongly resolved (because for git they look like a text).

When conflicts occur, git tries to automatically merge them. In some cases a LFS pointer conflict looks resolvable and git incorrectly merges it and breaks the LFS file format. After that Fork can only see that the file had a conflict in the past and it's already resolved now.

Currently the only way to prevent automatic merge I see is to mark files as binary. This seems to be correct, but may be there's a better solution.

(ref: there's a similar issue in the windows tracker https://github.com/ForkIssues/TrackerWin/issues/517)

**Comment by matteblair** [comment] 2021-02-10 22:04
I can confirm that adding the `binary` attribute to LFS files will make Fork use manual conflict resolution. Specifically, Fork seems to always use manual conflict resolution when the `diff` attribute is "unset" (this is one of the effects of the `binary` attribute).

This solves the original problem, but it also breaks Fork's file previews for LFS files. This is how LFS files are previewed with the "standard" LFS attributes `filter=lfs diff=lfs merge=lfs -text`
![image](https://user-images.githubusercontent.com/3371850/107578501-d0bf7300-6bc1-11eb-9186-269458abd4bc.png)


And this is how they are previewed with `filter=lfs diff=lfs merge=lfs binary`
![image](https://user-images.githubusercontent.com/3371850/107578453-c2715700-6bc1-11eb-93da-a82e2ea75b22.png)

The LFS file previews are a nice feature, and I'd prefer not to lose them!

**Comment by matteblair** [comment] 2021-02-10 22:17
Another strange facet of this issue is that Fork's merge conflict behavior is different for different kinds of files, even if the files have the exact same git attributes!

For example, when using the "standard" LFS attributes `filter=lfs diff=lfs merge=lfs -text` for both `.blend` and `.png` files, a merge conflict for a `.png` file will cause Fork to use manual conflict resolution, while a merge conflict for a `.blend` file (specifically, the one in my post above) will not. These files have the same attributes according to `git check-attr` and neither of them are considered "binary" according to `git diff --numstat`. This leads me to believe that this is a Fork behavior that can be improved without changes to git itself.

Another reason I believe this can be solved in Fork is that Sublime Merge correctly handles every type of LFS merge conflict I've tested so far ;)

**Comment by DanPristupov** [comment] 2021-02-12 10:50
@matteblair 
> adding the binary attribute to LFS files will make Fork use manual conflict resolution.
> ...
> This solves the original problem, but it also breaks Fork's file previews for LFS files.

I investigated this and can confirm that you are right :(.

The problem is that after adding `binary` (or `-diff`) attribute git doesn't mark files as LFS anymore.

1. .gitattributes: `*.dll filter=lfs diff=lfs merge=lfs -text` shows LFS output as expected:

```
$ git diff fc1aebe~1 fc1aebe roboto.ttf

diff --git a/roboto.ttf b/roboto.ttf
new file mode 100755
index 0000000..c4af590
--- /dev/null
+++ b/roboto.ttf
@@ -0,0 +1,3 @@
+version https://git-lfs.github.com/spec/v1
+oid sha256:b2efabca5ea4bc56eea829713706b5cd0788b82aca153bd4adde9b1573933b4f
+size 145348
```

2. .gitattributes: `*.dll filter=lfs diff=lfs merge=lfs binary` says that file is just plain binary and doesn't mention LFS at all. That's why Fork doesn't show the file details.

```
$ git diff fc1aebe~1 fc1aebe roboto.ttf

diff --git a/roboto.ttf b/roboto.ttf
new file mode 100755
index 0000000..c4af590
Binary files /dev/null and b/roboto.ttf differ
```

P.S. `binary` is an [alias](https://www.git-scm.com/docs/gitattributes#_defining_macro_attributes) for `-text -diff -merge`. `-` means `not`, so `binary` is basically `[not]text [not]diff [not]merge`. I tried different combinations of those attributed, but only `-diff` solves the problem with merge but also prevents git from showing file as LFS.

**Comment by DanPristupov** [comment] 2021-02-12 11:25
I think I made some incorrect assumptions on this problem initially. I'm going to work on this issue closely next week.

**Comment by DanPristupov** [comment] 2021-03-27 14:36
In Fork 2.6 we reworked the merge. Now it allows to merge images, binary files, submodules and also LFS files.

This particular problem must also be resolved. When you have a chance to try it, can you share some feedback, please?

**Comment by matteblair** [comment] 2021-03-27 19:56
I tested version 2.6 on macOS and it seems like the original issue is resolved. Merge conflicts in LFS files now correctly appear as conflicts. After choosing a version of the file in the merge interface, the committed file has the correct contents and not a conflicted pointer file. 
<img width="1016" alt="Screen Shot 2021-03-27 at 3 46 07 PM" src="https://user-images.githubusercontent.com/3371850/112733014-d7a50980-8f13-11eb-8e70-9be0b55202a2.png">

Note that I am _not_ using the `binary` attribute on the files here. Files with the `binary` attribute continue to appear as non-LFS files. However since the original issue is resolved it is no longer necessary to use that as a work-around.

Thank you for fixing this!

**Closed as completed** 2021-06-21 10:05 UTC
