### ISSUE TITLE
Changes count is not updated

### ISSUE THREAD

**Issue by neemanjabu** [ForkIssues/Tracker#376] opened 2018-08-07 23:23 UTC
- OS: Mac OS X El Capitain 10.1.16
- Fork: 1.0.69.4

Steps to reproduce:

- Make change in one file
- Changes count updated to 1
- Commit and push previously made update

Expected result:

- Changes count does not exist

Result:

- Changes count remains the same

![fork_changes_issue](https://user-images.githubusercontent.com/2862818/43807593-7d6b00b6-9aa9-11e8-8edc-1ce40eeca3ce.png)

**Comment by DanPristupov** [comment] 2018-08-08 05:55
Can you reproduce this problem twice?

**Comment by neemanjabu** [comment] 2018-08-08 21:12
Yes, it happens every time changes are made or discarded.
Count is updated correctly only if repository is closed and reopened.

**Comment by BrElio** [comment] 2018-09-19 17:05
Same issue here with:

Mac OS X El Capitain 10.11.6
Fork 1.0.70

**Comment by DanPristupov** [comment] 2018-09-19 19:05
@BrElio do you know how to reproduce the issue?

**Comment by BrElio** [comment] 2018-09-20 09:12
Hi, there's nothing to do to replicate it, the issue is there since I launch the program.
When it starts it shows the correct number of changes to commit. If I make any other change it won't update. If I stage and commit the changes the number doesn't update either.

**Comment by DanPristupov** [comment] 2018-12-01 16:00
This might be fixed in 1.0.72

**Closed as completed** 2019-02-01 10:28 UTC
