### ISSUE TITLE
[Bug] unicode normalization problem

### ISSUE THREAD

**Issue by GomPam** [ForkIssues/Tracker#444] opened 2018-10-24 01:32 UTC
mac use to NFD and windows is NFC mechanism. so, we get this normaliztion problem.
user text (like commit message, author..) display different between mac and windows if not used alphabet.
can you fix it?

Link: https://en.wikipedia.org/wiki/Unicode_equivalence

**Comment by alkee** [comment] 2019-01-25 10:32
Voting up.
I need really this as Korean user in file names and commit messages.

**Comment by kueecc** [comment] 2019-02-07 02:22
+1

**Comment by sckimos** [comment] 2019-03-20 19:20
+1

**Comment by kueecc** [comment] 2019-05-02 01:55
Any updates?

**Comment by DanPristupov** [comment] 2019-05-02 18:46
How is that supposed to be fixed?

**Comment by GomPam** [comment] 2019-05-03 04:12
@DanPristupov 
As far as I know, SourceTree is known to be fine.

**Comment by alkee** [comment] 2019-05-10 03:15
simply in swift, just make sure always use NFC encoding from user input like commit message and file path

```swift
   let nfd = "맥과 윈도우즈는 한글 저장방식이 다릅니다.ext" // string by user input
   let nfc = nfd.precomposedStringWithCanonicalMapping // converting to nfc
   // now, you can use `nfc` instead of `nfd`
```

little more detailed in 
  * https://jongampark.wordpress.com/2008/07/21/unicode-normalization-and-nsstring/

**Comment by GomPam** [comment] 2019-05-10 08:43
@alkee good infomation 👍 
@DanPristupov  need more infomation?
we need a feedback :)

**Comment by DanPristupov** [comment] 2019-05-11 13:05
I'm still not really sure why the problem happens and what should be a correct solution for that (from the Apple point of view). Are developers supposed to convert every input string? What will happen with other languages after that?

However I made a small test.

Made a `"맥과 윈도우즈는 한글 저장방식이 다릅니다.ext"` commit in Mac, and in Windows it became unreadable as you said.
Made a `"맥과 윈도우즈는 한글 저장방식이 다릅니다.ext"` commit in Windows. Everything seems to be correct on both platforms.

However passing strings in nfc form (using precomposedStringWithCanonicalMapping) to git process doesn't change anything. The string is still corrupted.

**Comment by alkee** [comment] 2019-05-13 01:24
Sorry for the not worked way. It's OS specific behavior for unicode, so there is no correct solution. In the point of git (not an Apple), they support configuration for the issue.

Can you test one more thing with the git config [core.precomposeunicode](https://www.git-tower.com/help/mac/faq-and-tips/faq/unicode-filenames) ?

`git config --global core.precomposeunicode true` 

It worked well with terminal git and happy to other platforms.

**Comment by GomPam** [comment] 2019-05-13 01:39
um.. i make that sample repository
https://github.com/GomPam/UnicodeNormalizeTest

* MacOSX
![스크린샷 2019-05-13 오전 10 25 46](https://user-images.githubusercontent.com/4710038/57590942-cd6d0280-7569-11e9-8ea4-95f93e19bf51.png)

* Windows
![스크린샷 2019-05-13 오전 10 26 19](https://user-images.githubusercontent.com/4710038/57590960-e37ac300-7569-11e9-8a30-51601c8c6387.png)

i use to same sentence.
> 유니코드 정규화 확인을 위한 문장. And Check With Alphabet.

**Comment by GomPam** [comment] 2019-05-13 01:43
@alkee "core.precomposeunicode" config is affects filenames.
> https://git-scm.com/docs/git-config#Documentation/git-config.txt-coreprecomposeUnicode
`... When core.precomposeUnicode=true, Git reverts the unicode decomposition of filenames done by Mac OS.`

so... i think its not working.. :(

**Comment by GomPam** [comment] 2019-05-15 08:09
@DanPristupov 
i make little program. 
just print "arg + hex string"
and then i understand what you said.
> However passing strings in nfc form (using precomposedStringWithCanonicalMapping) to git process doesn't change anything (I used `NSProcess().arguments`). The string is still corrupted.
(https://github.com/ForkIssues/Tracker/issues/444#issuecomment-491509557)

so
i think a trick.
make temp shellscript then execute it.
https://gist.github.com/GomPam/3986e317774085e3fb25cb5c00be0dd0

maybe i think this work.

**Comment by GomPam** [comment] 2019-05-28 03:29
@DanPristupov 
can we use this way.. or not?
update plz :)

**Comment by DanPristupov** [comment] 2019-05-28 06:49
I will not wrap every git request into an `sh` script.

However I want to try to pass the commit message using `git commit --file=...` command. May be it will be encoded properly.

**Comment by GomPam** [comment] 2019-05-29 02:01
@DanPristupov 
that way is better than me and works right!
when can we see apply that??

====

https://gist.github.com/GomPam/a801af883073f2cbad5747de5eca6443
https://github.com/GomPam/UnicodeNormalizeTest

![캡처](https://user-images.githubusercontent.com/4710038/58523784-b2082580-8200-11e9-9ea2-2c012526b8d5.PNG)

**Comment by GomPam** [comment] 2019-06-21 03:12
@DanPristupov 
um.. any update?

**Comment by hrs-o** [comment] 2019-06-25 07:16
Is #656 the same problem?

**Comment by GomPam** [comment] 2019-06-25 07:40
@hrs-o 
i think probably same problem.

**Comment by GomPam** [comment] 2019-07-26 01:46
@DanPristupov when do you plan to include this issue in the milestone?
1.0.82? 1.0.83? or more later?

**Comment by jun0683** [comment] 2019-11-21 06:34
+1

**Comment by DanPristupov** [comment] 2019-12-10 18:01
Hi. Could you try if the problem is fixed in that version (1.0.87.5): https://fork.dev/update/files/Fork.dmg?

It's not available for update yet.

**Comment by GomPam** [comment] 2019-12-11 00:38
@DanPristupov 
its been a while since your last comment :)

its probably successfully working!

Commit Message: 
>[Mac OSX] TestCommit 1.0.87.5 - 한글, ひらがな, 你好吗, Alphabet
>한글,
>ひらがな,
>你好吗,
>Alphabet

![스크린샷 2019-12-11 오전 9 29 43](https://user-images.githubusercontent.com/4710038/70581179-a8249d80-1bf9-11ea-924d-68684848b962.png)

On Windows:
![스크린샷 2019-12-11 오전 9 32 48](https://user-images.githubusercontent.com/4710038/70581250-ee79fc80-1bf9-11ea-9d3d-9e9cfad4f8e2.png)

Thanks, @DanPristupov

**Comment by DanPristupov** [comment] 2019-12-11 07:26
Let's wait for the 1.0.88 update. I'm not sure if this change will not make any problems for other users.

However unicode docs (http://www.unicode.org/faq/normalization.html#2) say it should be OK:

> Q: Which forms of normalization should I support?
> 
> A: The choice of which to use depends on the particular program or system. **NFC is the best form for general text, since it is more compatible with strings converted from legacy encodings.** NFKC is the preferred form for identifiers, especially where there are security concerns (see UTR #36). NFD and NFKD are most useful for internal processing.

**Comment by DanPristupov** [comment] 2019-12-13 15:04
I just released 1.0.88. Could you double check that everything still works please?

**Comment by jun0683** [comment] 2019-12-16 00:01
yes~ it is fixed. awesome~

**Comment by GomPam** [comment] 2019-12-16 01:54
@DanPristupov 
Hi. i think probably working great
all (google supported language) of the unicode commit message is fine

commit on mac (fork 1.0.88)
https://github.com/GomPam/UnicodeNormalizeTest/commit/df02f40cd967e88920014b4ed2cd0fbe2058d8c0

and then windows
![스크린샷 2019-12-16 오전 10 51 42](https://user-images.githubusercontent.com/4710038/70873676-17333500-1ff2-11ea-9d9a-f3a8387f3a18.png)

**Comment by kueecc** [comment] 2019-12-17 12:17
It works perfectly! Thank you very much!

**Closed** 2019-12-17 14:40 UTC
