### ISSUE TITLE
[Feature Request] Remember and open previous repos when reopening on OSX

### ISSUE THREAD

**Issue by pdevito3** [ForkIssues/Tracker#1449] opened 2021-08-23 21:57 UTC
On windows, if you close and reopen for, it will continue to show the repos you had open when it closed. on osx, it will open fresh with no repos open on every reopen. it would be great if it could remember the open tabs and keep them open when opening fork again. would save me a lot of time.

**Comment by DanPristupov** [comment] 2021-08-24 06:40
If you close Fork using Cmd+Q, it will remember the tabs.
I think this is a duplicate of https://github.com/fork-dev/Tracker/issues/641

**Comment by pdevito3** [comment] 2021-08-24 17:41
Even if that's true, should I really be forced to remember to close that way?

**Comment by DanPristupov** [comment] 2021-08-24 18:05
> Even if that's true, should I really be forced to remember to close that way?

It works the same in all MacOS applications. For example in Safari and XCode. Yes, I'm forced to remember and close Safari using Cmd+Q :(

**Comment by DanPristupov** [comment] 2023-06-08 09:47
Starting 2.27 Fork manages the application windows manually and restores tabs on close.

**Closed as completed by DanPristupov** 2023-06-08 09:47 UTC
