### ISSUE TITLE
Adjust Sort Order of Tags

### ISSUE THREAD

**Issue by nebhale** [ForkIssues/Tracker#213] opened 2018-02-12 21:06 UTC
Currently, the sort order of tags is lexically ascending.  For most projects, this is probably fine, but I maintain a project where my 27" iMac screen isn't going going to be enough to see the tags without scrolling.

![screen shot 2018-02-12 at 13 01 31](https://user-images.githubusercontent.com/60754/36119635-6860c0b4-0ff5-11e8-98db-72a616237644.png)

It'd be nice to adjust the sort order from ascending to descending for these tags (although this is probably a broader UI request) since I mostly care about the latest tags rather than the oldest tags.

**Comment by clounie** [comment] 2018-02-12 21:46
Or for that matter, just being able to sort ALL the categories :)

(Tags, Branches, Remotes, etc)

**Comment by DanPristupov** [comment] 2018-02-13 09:54
Hi.

Yes, I see the problem. Not sure how to solve it though.

Thinking out loudly:
- I can add an option button near the 'Tags' header, which will show a dropdown with sorting options (similar to one near the Repository name). Not sure if many people will find such an option useful.
- May be we need to improve a filter instead and allow to set filters for tags and branches separately. Like `v.4.7*`. Also @clounie's proposal to move the filter field up can be very useful there https://github.com/ForkIssues/Tracker/issues/84

Is there any other approach?

**Comment by nebhale** [comment] 2018-02-13 14:04
There’s already a context menu on the “Tags” header, maybe add sort order into that (and the equivalents) menu?  Doesn’t pollute the main UI for most people who don’t care, and gives those of us who do a way to change the order.

**Comment by DanPristupov** [comment] 2019-02-15 16:14
I added branch branch/tag sorting to Fork 1.0.74. Please check for updates.

<img width="368" alt="screenshot 2019-02-15 at 17 12 49" src="https://user-images.githubusercontent.com/618115/52868980-ecafeb80-3144-11e9-9f59-96ec53c38025.png">

**Comment by nebhale** [comment] 2019-02-21 14:49
I’ll have a look today, but what constitutes “recently used” when I see it?  Is it creation date for tags?

**Comment by DanPristupov** [comment] 2019-02-21 15:06
It's date of the corresponding commit the tag points to.

You can see the date in the tooltip:
<img width="250" alt="image" src="https://user-images.githubusercontent.com/618115/53178484-393a7180-35f2-11e9-9016-af84576b6e80.png">

**Comment by nebhale** [comment] 2019-02-21 16:38
Verified.  Exactly what I was looking for.

**Comment by DanPristupov** [comment] 2019-02-21 17:18
Great! Closing this issue then.

**Closed by DanPristupov** 2019-02-21 17:18 UTC

**Comment by gsbernstein** [comment] 2025-02-13 02:36
What's the intended behavior for tags with directories? (eg `v99.0.0/test`). It seems like if I do "recently used" sorting, it still ends up at the very bottom, even if the commit is pretty recent. Maybe a "recently used, master and folders on top" option would be helpful, like for the alphabetical one. (sorry for bumping such an old ticket, but I didn't see it discussed anywhere else)
