### ISSUE TITLE
"Fatal error" after resolving rebase conflict

### ISSUE THREAD

**Issue by nsh-ableton** [ForkIssues/Tracker#956] opened 2020-03-31 11:27 UTC
Sometimes when I've resolved a conflict during an interactive rebase, and I continue the rebase, I get the following error message in Fork:

```
2020-03-31 13:23:35.862 fork_ri[9849:9035234] Start helper for editing COMMIT_EDITMSG.
Fatal error: String index is out of bounds
error: "/Applications/Fork.app/Contents/Resources/fork_ri" died of signal 4
error: There was a problem with the editor '"/Applications/Fork.app/Contents/Resources/fork_ri"'.
Please supply the message using either -m or -F option.
error: could not commit staged changes.
```

This has only started happening with 1.0.90. (I just updated to 1.0.91.1 and it's still going on.) I'm able to continue the rebase from the command line with `git rebase --continue` without problems.

**Comment by DanPristupov** [comment] 2020-03-31 11:36
I just checked, we did not introduce any change to IR in 1.0.87-1.0.90.

What git instance do you use in Fork?

**Comment by nsh-ableton** [comment] 2020-03-31 11:44
I haven't changed it from the 2.23.0 Fork instance. I'll switch it to 2.25.0, which is the one I'm using on the command line, and see if the issue persists.

**Comment by nsh-ableton** [comment] 2020-03-31 14:33
Changing the git instance to match what I use in the command line does not help. I still get the same error.

**Comment by DanPristupov** [comment] 2020-03-31 15:02
When the problem occurs next time, could you send the following files to support@fork.dev please?

`.git/rebase-merge/git-rebase-todo`
`.git/rebase-merge/done`

You can edit them, if needed.

**Comment by nsh-ableton** [comment] 2020-04-01 14:46
Do you think it's possible that the contents of some of the commit messages are causing problems? I am, recently, using a lot of commit messages that begin with square brackets (as in "`[wip]`"). I'd kind of need to edit out most of the contents of the messages before sending the files to you, so I'm not sure how useful they'd be.....

**Comment by DanPristupov** [comment] 2020-04-01 15:32
> Do you think it's possible that the contents of some of the commit messages are causing problems?

Messages line `[wip]` should not be a problem.
Is that possible that one of your commits contained multiline message which was separated with a single `\n` instead of recommended `\n\n`? (You can't create commit with such a message in Fork)

**Comment by nsh-ableton** [comment] 2020-04-07 19:31
Sorry for the slow response — this does seem to happen in situations where a fixup has resulted in one of those commit messages that temporarily looks like
```
# This is a combination of 3 commits.
# This is the 1st commit message:

Blah blah blah blah

Some more blah blah blah blah, blah blah.....
```
Could the lines with the `#`s be tripping something up?

**Comment by DanPristupov** [comment] 2020-04-07 20:16
Good point. I will investigate tomorrow.

**Comment by DanPristupov** [comment] 2020-04-08 11:13
OK, regarding the latest (https://github.com/ForkIssues/Tracker/issues/956#issuecomment-610578181). Here's what I found out:

There's a case which isn't handled fluently (however, it's not a bug). It happens when we make reorder + fixup which causes conflict. For example:

<img width="158" alt="Screenshot 2020-04-08 at 12 58 33" src="https://user-images.githubusercontent.com/618115/78776745-a8128f80-7998-11ea-9c34-afa9f9bad2df.png">

Internally git performs fixup as amend, so after we get a conflict, we end up in the rebase-**amend** state. This is why you see that commit message.

In order to proceed we must resolve the conflict, stage the changes then **enable amend and commit**. Then everything works properly. This is not obvious, of course.

I improved the behavior and in the next update, when the fixup-conflict case happens, Fork will automatically activate the amend mode. The rest will be intuitive.

However, I think this is not related to the original issue you reported.

Summary. As for now, if you encounter this again just enable amend. When you update Fork to the next release (1.0.92, will come out on Friday), please give me some feedback.

**Closed as completed** 2020-06-01 07:42 UTC
