### ISSUE TITLE
Bitbucket shows only a subset of repos to clone

### ISSUE THREAD

**Issue by kambala-decapitator** [ForkIssues/Tracker#1362] opened 2021-04-22 06:04 UTC
My Bitbucket account is in multiple teams and I have access to tens of repos, but in the clone window I see only 10. Looks like it's the first page of response (or a bug in UI), as the repos I see are from one of the teams and in alphabetical order. I don't even see my personal repos!

v2.6.1 (I use `develop` update channel), Catalina

**Comment by DanPristupov** [comment] 2021-04-22 08:57
I confirm the problem

**Comment by DanPristupov** [comment] 2021-04-22 09:22
Can you check if the problem is fixed in this build, please? https://cdn.fork.dev/prerelease/Fork-2.6.9.dmg

**Comment by kambala-decapitator** [comment] 2021-04-22 09:30
> Can you check if the problem is fixed in this build, please? https://cdn.fork.dev/prerelease/Fork-2.6.9.dmg

works fine! thanks!

**Comment by DanPristupov** [comment] 2021-04-22 09:41
The fix will be a part of the 2.7 update (it's planned for tomorrow)

**Closed as completed** 2021-04-25 09:11 UTC
