### ISSUE TITLE
crash on creating new branch

### ISSUE THREAD

**Issue by kambala-decapitator** [ForkIssues/Tracker#2048] opened 2024-01-21 10:26 UTC
v2.38, constantly reproducible. The repo where I'm trying to create branch is a worktree, if it matters. If I click on the currently checked out branch on the left first, then there's no crash when creating branch from the toolbar.

[Fork-2024-01-21-132340.ips.txt](https://github.com/fork-dev/Tracker/files/14000907/Fork-2024-01-21-132340.ips.txt)

https://github.com/fork-dev/Tracker/assets/1557784/2f97cd4e-320d-420f-9e2d-66803adac1c2

**Comment by DanPristupov** [comment] 2024-01-21 11:18
Thank you. I've reproduced the problem.

**Comment by DanPristupov** [comment] 2024-01-21 11:19
Do you need a hotfix *right now*? Or can you wait?

**Comment by kambala-decapitator** [comment] 2024-01-21 11:20
> Do you need a hotfix _right now_? Or can you wait?

thank you very much, but I'm good :)

**Comment by DanPristupov** [comment] 2024-01-26 17:13
The problem is fixed in Fork 2.39.

Thank you very much for the bug report 👍

**Closed as completed** 2024-02-19 08:34 UTC
