### ISSUE TITLE
Remote git repo

### ISSUE THREAD

**Issue by oliverhu** [ForkIssues/Tracker#2096] opened 2024-03-24 03:55 UTC
Does Fork support managing repos in a remote machine? I have been using Fork to manage local repos on macOS, but I also hope to manage repos in a remote desktop.

**Comment by DanPristupov** [comment] 2024-03-26 14:21
No, Fork requires direct access to the files.
This is a duplicate of https://github.com/fork-dev/Tracker/issues/929

**Closed as completed** 2024-04-19 15:48 UTC
