### ISSUE TITLE
 Unable to add Gitlab access

### ISSUE THREAD

**Issue by kmander** [ForkIssues/Tracker#310] opened 2018-06-12 21:09 UTC
Unable to log in with Gitlab using either basic authentication or a personal token.

<img width="596" alt="screen shot 2018-06-12 at 14 04 16" src="https://user-images.githubusercontent.com/1092245/41317298-a05e8520-6e49-11e8-8f3b-846bd0d8682c.png">

Looking at the Console log and doing some digging, it appears to be related to using a now outdated version of the Gitlab API. Error spotted:

`{"error":"API V3 is no longer supported. Use API V4 instead."}`

**Comment by DanPristupov** [comment] 2018-06-14 13:45
Yes, I can confirm, this is a problem in Fork. I can't make it work **right now**, because I'm in the middle of a huge task. So, I'll fix it as soon as I get free (during next week, probably).

Sorry for the inconvenience.

P.S. This problem should not affect the ability to fetch and push to gitlab-based repositories anyway.

**Comment by DanPristupov** [comment] 2018-09-18 05:14
Fixed in 1.0.70

**Closed** 2018-10-11 13:58 UTC
