### ISSUE TITLE
[bug] Pushing to create a new branch pushes to master branch instead

### ISSUE THREAD

**Issue by thecristen** [ForkIssues/Tracker#1587] opened 2022-04-13 17:47 UTC
Steps to reproduce my particular case:

* push `my_branch` to `origin1/master`
* then at some later iteration...
* push `my_branch` to... change selected origin to `origin2`, it now shows `To: new (origin2/my_branch)` (this is the desired goal)
* push
* it ends up pushing to `origin2/master` (unwanted!)

**Comment by DanPristupov** [comment] 2022-04-13 19:35
Could you check what remote-tracking reference the branch has? You can see that in the tooltip over the branch on the sidebar.

**Comment by thecristen** [comment] 2022-04-13 20:08
Just checked, it's `origin1/master`

**Comment by DanPristupov** [comment] 2022-04-26 15:44
I can't reproduce the problem.

Here's what I just did:

1. The test repository has 2 remotes: `origin` and `gitlab.com`

2. Create a local branch `br1`.
<img width="245" alt="Screenshot 2022-04-26 at 17 36 05" src="https://user-images.githubusercontent.com/618115/165338636-3d7d0836-5264-4148-a761-b5ab1f1086da.png">

3.  Push `br1` to `origin`, with enabled 'Create Tracking Reference'
<img width="494" alt="Screenshot 2022-04-26 at 17 36 20" src="https://user-images.githubusercontent.com/618115/165338696-d33a5c4e-a726-414b-8241-253df64a0de3.png">
<img width="331" alt="Screenshot 2022-04-26 at 17 36 49" src="https://user-images.githubusercontent.com/618115/165338876-f0c66bbf-961b-44a1-9100-f9176ee5812b.png">

4. Open Activity Manager in Fork and confirm that the branch was pushed to `origin/br1`
<img width="782" alt="Screenshot 2022-04-26 at 17 36 40" src="https://user-images.githubusercontent.com/618115/165338804-7dd92884-54db-4268-9523-a3ae21bb3d8b.png">

5. Push `br1` to another remote which is called `gitlab.com`:
<img width="488" alt="Screenshot 2022-04-26 at 17 37 10" src="https://user-images.githubusercontent.com/618115/165338986-ed52a054-aaf3-481e-a312-5db55928eac0.png">
<img width="431" alt="Screenshot 2022-04-26 at 17 37 41" src="https://user-images.githubusercontent.com/618115/165339017-021a12bf-9935-46cb-bdc3-df30aa5f3671.png">

6. Open Activity Manager and confirm that the branch was pushed to `gitlab.com/br1`
<img width="666" alt="Screenshot 2022-04-26 at 17 37 33" src="https://user-images.githubusercontent.com/618115/165339116-d4334851-7578-416a-b4b4-790c6b6d61e1.png">

Everything seems to be correct.
Am I missing something?

**Comment by thecristen** [comment] 2022-04-26 17:18
Thanks for looking into this.

Correction: To replicate my case, the first push would be to `origin/master` rather than `origin/br1`.
The second push would stay the same as you wrote it, to `gitlab.com/br1`. And if my problem reproduces for you it might push to `gitlab.com/master` instead!

**Comment by DanPristupov** [comment] 2022-04-26 19:16
Thank you, I've reproduce that 👍

**Comment by vfonic** [comment] 2022-10-20 17:29
I just encountered this issue. I pushed the open-source project and, instead of pushing to non-master branch, it pushed to `master` branch. Luckily there was no automatic deployment or new version of the open-source library automatically released. It's quite scary that this happened.

Here's what I did:
1. `git clone` a project
2. Add a different remote, let's call it `origin-fork` which has a few different commits on some branch, the easiest is if there are few extra commits on `origin-fork/master`
3. Checkout `origin-fork/master`, Fork.app will complain that you already have a branch called `master` (tracking `origin/master`). Name the new branch something else: `master-fork`
4. CMD+SHIFT+P / Push -
  Branch: `master-fork`
  Remote: Choose `origin`
  To: `new (origin/master-fork)`

Expected:

New branch is created on `origin` remote and it's pushed to.

Actual:

`$ git push origin refs/heads/master-fork --tags --verbose` is executed, which pushes to `origin/master`

**Comment by DanPristupov** [comment] 2022-10-20 19:29
@vfonic

I created the following configuration with 2 remotes (`origin` and `gitlab`):
`develop -> origin/develop`
`develop-gitlab -> gitlab/develop`

Then checkout `develop-gitlab`, open Push, change the remote to `origin`.

But there's no destination `new (origin/develop-gitlab)`. I only see To: `origin/develop`.

--

Does your `master-fork` branch have a valid remote tracking reference?

**Comment by vfonic** [comment] 2022-10-20 20:47
I just updated Fork from 2.15.1 to 2.21 and I see the same like you. I guess this has been fixed recently?

**Comment by DanPristupov** [comment] 2022-10-21 06:44
<img width="455" alt="Screenshot 2022-10-21 at 8 43 52" src="https://user-images.githubusercontent.com/618115/197130362-39d33b2d-cdcc-46ea-bf96-75ebbb4cd929.png">

Yes, in `2.18`

**Comment by vfonic** [comment] 2022-10-21 16:03
Ah great! Thanks for fixing that!

I assume you can close this issue now. I don't have the permissions since I wasn't the one who opened it.

**Closed as completed** 2022-10-21 19:53 UTC
