### ISSUE TITLE
Repositories not updated after clone

### ISSUE THREAD

**Issue by SkywardRay** [ForkIssues/Tracker#853] opened 2019-12-27 14:57 UTC
I'm using Fork 1.0.88 on Mac Mojave 10.14.6.

I would expect that cloning a repo would open the repo after it is done. If that is not desired behavior I would expect it to at least update the list of repositories in the repository manager. Both don't seem to happen. 

Am I doing something wrong?

**Comment by DanPristupov** [comment] 2019-12-27 15:04
Are you sure the clone succeeded?

If so, can you write steps to reproduce the problem?

**Comment by SkywardRay** [comment] 2019-12-27 15:38
Current steps to clone a repository:
- click clone in the file menu.
- url is automatically inserted and folder is correct, press 'clone'.
- progress bar at top of window shows busy, then completed.
- nothing changes in the rest of the window.
- right click in repository section and click 'Rescan Repositories...'
- repository that was cloned shows up and I click to open it.

So I am able to successfully clone and open a repo. I just don't understand why it doesn't open by itself

**Comment by DanPristupov** [comment] 2019-12-27 16:07
Yes, I confirm the bug. Thank you. Looks like I've broken that behavior recently :)

**Comment by L1cardo** [comment] 2020-01-01 13:27
I want this too.
Now I have to rescan everytime I finish cloning a repo, in order to make it appear in the repo manager.
It would be nice if it automatically shows up after cloning, or automatically open itself.
Clone, rescan, open.. this is annoying

**Comment by DanPristupov** [comment] 2020-01-24 14:41
Fixed in 1.0.89.

**Closed as completed by DanPristupov** 2020-01-24 14:41 UTC
