### ISSUE TITLE
Unstaged / Staged / Commit Message UI is confusing / incorrect

### ISSUE THREAD

**Issue by tjluoma** [ForkIssues/Tracker#939] opened 2020-03-22 13:02 UTC
This is a little tricky to describe, but I will try.

1. Assume you have 2 or more files listed in "Unstaged Changes"

2. You select 1 of the files, which makes the changes appear in the large preview in the area which shows additions/deletions

3. You press "Enter" which moves the file from "Unstaged Changes" to "Staged Changes"

4. You press Command + Shift + C to write a Commit Message

5. However, the file which is now previewed in the large preview area on the right is now the next file in "Unstaged Changes"

6. You have to click on the file in "Staged Changes" using the mouse/trackpad to get its preview to appear. I have not found any way of doing this via the keyboard alone.

It seems like when you do Step 4 and indicate that you want to write a Commit Message, the file in "Staged Changes" should be selected automatically. Otherwise, if you don't notice what has happened, you might look at the additions/deletions pane and write the wrong commit message because you are not looking at the staged file.

Hopefully this makes sense. If not, please let me know.

**Comment by DanPristupov** [comment] 2020-03-23 08:16
OK, closing as a duplicate of https://github.com/ForkIssues/Tracker/issues/514.

**Closed as completed by DanPristupov** 2020-03-23 08:16 UTC
