### ISSUE TITLE
Some english characters cannot be input in any fields

### ISSUE THREAD

**Issue by nelson-chim** [ForkIssues/Tracker#236] opened 2018-03-02 09:14 UTC
Sometimes I cannot type "p","r","s","d","f" in any input fields.
Kill and restart app resolves the problem.

I am using Fork ver. 1.0.64.1 and macOS Sierra 10.12.6

**Comment by DanPristupov** [comment] 2018-03-02 09:27
Hi. This is a bug introduced in the recent version. I'll fix it in the next update.
More info there: https://github.com/ForkIssues/Tracker/issues/174
Please let me know if you find how to reproduce this.
Sorry for the inconvenience.

**Comment by nelson-chim** [comment] 2018-03-02 09:36
I will try to keep track for the reproduce pattern.
Thanks for reply.

**Comment by gaggle** [comment] 2018-03-11 14:49
I've also had the issue of not being able to use keys used by shortcuts anywhere in the app after using interactive rebase, but have also not been able to reproduce it :) I too am on 1.0.64.1, and macOS 10.13.3.

To verify, the problem manifested itself globally e.g. I couldn't type letter "P" into the commit or Create Branch dialog boxes. Restarting the app would solve the issue.

I keep checking after each rebase but haven't had a repro so... *shrug* Thanks for looking into it.

**Comment by DanPristupov** [comment] 2018-03-12 14:24
Even though I could not reproduce that bug anymore, I made some changes which should fix the issue.

I released a hotfix build, could you guys try it and let me know if I'd solved the issue?
https://git-fork.com/update/files/Fork-v1.0.64.2.dmg

Thank you in advance

**Comment by nelson-chim** [comment] 2018-03-12 14:47
Will have a try later. Thanks

**Comment by DanPristupov** [comment] 2018-03-20 08:54
This should be fixed in the later version (1.0.65).

**Closed** 2018-05-21 16:16 UTC
Labels: done
