### ISSUE TITLE
Commit greyed out when using cursor to select last commit text

### ISSUE THREAD

**Issue by MartinSchultz** [ForkIssues/Tracker#744] opened 2019-09-15 07:05 UTC
If I click with the mouse cursor in the commit subject field, press cursor up for the last commit message and then return to have the last commit text in the commit subject field, the button "commit" is not activated. I first need to do any change in the text subject field to have the button active - so that I can commit. Looks to me like a bug and worked in previous versions. Thanks!

**Comment by DanPristupov** [comment] 2019-09-15 11:40
Looks like a duplicate of https://github.com/ForkIssues/Tracker/issues/740

I'll fix this in the next update.

**Comment by DanPristupov** [comment] 2019-09-25 07:07
Fixed

**Closed as completed by DanPristupov** 2019-09-25 07:07 UTC
