### ISSUE TITLE
Unable to compare 2 commits with paths with umlauts

### ISSUE THREAD

**Issue by Tunous** [ForkIssues/Tracker#1767] opened 2022-12-14 10:55 UTC
Happens in Fork for macOS 2.24.1.

Reproduced if one of selected commits or any commit between them affects file that has polish letters in name (ąćęłńóśźż).

![Screenshot 2022-12-14 at 11 50 16](https://user-images.githubusercontent.com/5156340/207575711-2b80fa1b-e234-46f1-9119-abf58b45a460.png)

**Comment by DanPristupov** [comment] 2022-12-14 11:01
Can you see diff of each separate commit in the selected range?

**Comment by Tunous** [comment] 2022-12-14 11:02
Yes, if I select commits individually I can see all their changes.

**Comment by DanPristupov** [comment] 2022-12-14 11:03
Thank you. If the problem is critical, you can download `2.23.1` here: https://cdn.fork.dev/mac/Fork-2.23.1.dmg

**Comment by DanPristupov** [comment] 2023-01-16 08:39
The problem must be fixed in Fork 2.25

**Comment by Tunous** [comment] 2023-01-16 08:46
Confirmed it is fixed after update to 2.25.2

**Closed as completed** 2023-01-16 08:47 UTC
