### ISSUE TITLE
[Prerelease] Fork 1.0.68

### ISSUE THREAD

**Issue by DanPristupov** [ForkIssues/Tracker#318] opened 2018-06-21 14:10 UTC
Hi guys!

I migrated Fork to native macOS tabs and this was one of the biggest changes in Fork since the beginning. I made about 160 commits and updated almost every file in the project.

Now I need some public testing.

I spent a lot of time testing every particular feature myself, but people use different scenarios and there still could be things which I might miss. I would like to ask you to check that your workflow works good.

![2](https://user-images.githubusercontent.com/618115/41723874-88e730a2-756c-11e8-831d-491f7b124b1d.gif)

Some details: As you could know Fork got tabbed interface before Apple introduced that feature globally in macOS Sierra. I could not migrate Fork to Sierra at the time, but I can proceed now when the majority of users (97%) are up to date.

![1](https://user-images.githubusercontent.com/618115/41723870-8612686a-756c-11e8-9c34-17f97ac81dd0.gif)

So, the release covers the following issues:
- Multiple windows (https://github.com/ForkIssues/Tracker/issues/5)
- Use standard document behavior (https://github.com/ForkIssues/Tracker/issues/277)
- ⌘W should close last open window (https://github.com/ForkIssues/Tracker/issues/36)
- Only close current window by clicking the close button (https://github.com/ForkIssues/Tracker/issues/302)
- The option to hide tab bar if only one tab is open (https://github.com/ForkIssues/Tracker/issues/8)
- UI jumps during application start (https://github.com/ForkIssues/Tracker/issues/30)

Cons (i.e. what we are losing):
- tabs (on macos 10.11): 3% of Fork users will loose tabs, but will be able to use multiple windows
- color stickers: I didn't find a way to customize tab headers and could not reimplement color stickers

Please do not install the application. Run it right from the DMG file, it will allow you to use both old and new Fork versions.

⭐️ Download link [updated 10 Jul]: https://git-fork.com/update/files/Fork-1.0.68.3.dmg

**Comment by kissferenc** [comment] 2018-06-21 19:26
First thoughts:
 - I have to open all repository. So can't restore from previous session.
 - After I opend a repository, I don't see the plus button (and the tab bar). The tab bar was there in the previous version. So this is a bit uncomfortable.
 - the "Repository status" toolbar item is not showing anything when I first open a repository.

First opend repository:
<img width="406" alt="screen shot 2018-06-21 at 20 49 31" src="https://user-images.githubusercontent.com/2789309/41739499-85e0ef14-7595-11e8-81e3-1ec5c677cacd.png">

Every other repository:
<img width="387" alt="screen shot 2018-06-21 at 20 49 19" src="https://user-images.githubusercontent.com/2789309/41739512-90e8bf7c-7595-11e8-84b1-71add9fc56ea.png">

I restarted the program. But I had to reopen all windows and repositories again. This is very inconvenient. And the restart does'nt solved the "repostirory status" bug.

But I think this work will be awasome! Than you for sharing!

**Comment by DanPristupov** [comment] 2018-06-22 08:13
@kissferenc thank you very much for the feedback!

> I have to open all repository. So can't restore from previous session.

Good point! I will import the previous session to make the migration flawless.

> After I opened a repository, I don't see the plus button (and the tab bar). The tab bar was there in the previous version. So this is a bit uncomfortable.

I don't like this too, but this is the default behavior in macOS. The tab bar (including the <kbd>+</kbd> button) will appear **automatically** when you open a second repository. To make that easier, I made the OpenQuick dialog (<kbd>⌘</kbd><kbd>⇧</kbd><kbd>o</kbd>) always open repositories in new tab by default.

As an alternative you can enable tab bar manually in menu:
<img width="286" alt="2018-06-22 at 10 04" src="https://user-images.githubusercontent.com/618115/41765210-b7384030-7603-11e8-881c-a56fd463b319.png">

> the "Repository status" toolbar item is not showing anything when I open a repository.
Everything works properly on my computer. Is that easy to reproduce on your computer?

Just to remind myself:
* Save Stash button on the toolbar doesn't work. However Save Stash in application menu still works.

**Comment by kissferenc** [comment] 2018-06-22 13:41
@DanPristupov 
> As an alternative you can enable tab bar manually in menu

Yes I know this menu, and I always opend a repository by plus sign. I don't use the OpenQuick dialog becouse I have many folders that contains repositories. So I don't remember all repsoitory names :D. So as I sad this was a little bit unconfortable for me. And this is OK.

> How did you restart the program? The close button kills the session. When you close application with ⌘Q, the session will be saved/restored. Same as in Safari (or any other application).

You're right! In System Preferences -> General tab the "Close windows when quitting an app" was checked. After I unchecked, the sessions in every windows saved and restored perfectly.

> Everything works properly on my computer. Is that easy to reproduce on your computer?

Yes, becouse I restarted the App many times and does'nt solved the problem. I don't know why, becouse the old stable is working when I start it. ...
Oh! It's working now, I don't know why. I try to write down the steps:
- After I downloaded the prerelease I renamed the App to "Fork prerelase".
- I restarted app many times and does'nt solved the problem.
- I renamed the app to "Fork" and after restart does'nt solved the problem again.
- I started the stable version of Fork to check something...
- I unchecked the "Close windows when quitting an app" checkbox and restarted the app.
And now working the "Repository status" toolbar and I can't reproduce the problem. (I tried to rename app, tried to check the checkbox again....)

But I found a little problem again 🐰 

When I open a new window the File -> New Window menu has command+N keystroke. But when I open a repository the command+N keystroke is missing and the keystroke open the Clone dialog.

![screen shot 2018-06-22 at 15 20 39](https://user-images.githubusercontent.com/2789309/41779540-69724dbc-7632-11e8-9531-5312992a71d5.png)

![screen shot 2018-06-22 at 15 19 40](https://user-images.githubusercontent.com/2789309/41779552-6c32b91a-7632-11e8-8439-29cef546ac29.png)

**Comment by nsabovic** [comment] 2018-06-23 00:39
This is exactly what I was missing so sorely! Thank you so much for implementing this.

There are a few bugs, I think related to restoring windows.

1. When I use the command-line helper to open the current directory, two tabs are opened. One with the the repository I wanted, and one with the repository chooser, which no one asked for.
1. If I open the preferences window, and then close it, using command-line helper resurrects it again.
1. Window positions are not remembered. If I resize/move the window, the next time I open the app, it shows up at the original place.

I've made a quick screen recording showing these: 

![screen](https://user-images.githubusercontent.com/842998/41803894-fb4d17ac-7642-11e8-8fe2-09b801a45342.gif)

**Comment by kissferenc** [comment] 2018-06-23 12:54
@DanPristupov 

> Oh! It's working now, I don't know why.

When I open a new window while the previous window in full screen, then the "Repository status" toolbar isn't working. But when I exit from full screen the toolbar will be ok.

**Comment by kissferenc** [comment] 2018-06-24 08:40
Last night I closed the Fork with cmd+Q. I think 3 windows was open in full screen. Today I want to start and crashed.

![screen shot 2018-06-24 at 10 34 31](https://user-images.githubusercontent.com/2789309/41817406-d523d184-779a-11e8-9f97-8b2367ad8c01.png)

I reopend all windows but only 2 windows appear and one of them is not in full screen.
Here is the crash log: https://ufile.io/fews7

**Comment by kissferenc** [comment] 2018-06-24 09:17
Last night I closed the Fork with cmd+Q. I think 3 windows was open in full screen. Today I want to start and crashed.

![screen shot 2018-06-24 at 10 34 31](https://user-images.githubusercontent.com/2789309/41817406-d523d184-779a-11e8-9f97-8b2367ad8c01.png)

I reopend all windows but only 2 windows appear and one of them is not in full screen.
Here is crash log: https://ufile.io/fews7

**Comment by kissferenc** [comment] 2018-06-24 17:40
I realized the "Repository status" toolbar not updating at all in full screen window.

**Comment by DanPristupov** [comment] 2018-07-05 11:47
@kissferenc @nsabovic I polished a lot of things and released 1.0.68.2.

Here are the most notably changes:
- added diff view tab above every text control
- improved responsiveness of the flying buttons in the commit view
- made many visual improvements related to the upcoming macOS Mojave
- fixed opening two windows when open repository from CLI
- fixed incorrect status bar behavior in fullscreen mode
- fixed stash button
- fixed Cmd+N shortcut

1.0.68.2 can be downloaded there: https://git-fork.com/update/files/Fork-1.0.68.2.dmg

I'd be happy to hear your feedback.

**Comment by nsabovic** [comment] 2018-07-05 16:42
This version works great for me, thank you!

The preferences window is not coming back from the dead, but the about window is. That's the only bug I've seen so far.

**Comment by bwl21** [comment] 2018-07-06 09:17
I stay on Macos 10.11. Please do not remove support for this. Opening repositories in separate windows is ok.

**Comment by DanPristupov** [comment] 2018-07-10 08:34
We almost there

1.0.68.3:
- Added highlighting to git outputs (fetch/push, errors).
- Added possibility to show ignored files in the file list
- Added ability to hide remote branches in revision list
- Improved startup time, when running Fork from CLI tool
- Fixed `fork open` command (https://github.com/ForkIssues/Tracker/issues/315)
- Import Fork <1.0.67 sessions

<img width="500" alt="2018-07-10 at 10 24" src="https://user-images.githubusercontent.com/618115/42498387-5a0b2b0c-842c-11e8-9b23-6a833b0c18f9.png">

**Comment by luongvo209** [comment] 2018-07-10 13:55
Everything is working fine for me here on 1.0.68.3 :>

**Comment by luongvo209** [comment] 2018-07-11 03:51
@DanPristupov Hi Dan, I noticed one small bug. 
Steps to reproduce:
1. Open a window in `fork`.
2. Go to another project and open it in fork.
All the above commands are done with the command line `fork`. 
The second project opens well, but it leaves a ghost window for some reasons. 
Screenshot: 
<img width="1140" alt="screen shot 2018-07-11 at 10 48 40 am" src="https://user-images.githubusercontent.com/15828926/42549801-4de27304-84f8-11e8-825c-a2b6a5b8bc7f.png">

**Comment by DanPristupov** [comment] 2018-07-11 13:12
@luongvo209 thank you. Added to mu todo list. Will investigate later.

Otherwise I released 1.0.68 and where also introduced handling of github/bitbucket urls (https://github.com/ForkIssues/Tracker/issues/43)

**Comment by homm** [comment] 2018-07-11 19:34
> tabs (on macos 10.11): 3% of Fork users will loose tabs

😢

**Comment by Niels-NTG** [comment] 2018-07-12 13:19
Just downloaded the 1.0.68.4 release on my MacOS 10.13.5 machine. It doesn't seem able to remember the tabs I openend between sessions of the same version. Very annoying.

**Closed** 2018-07-19 15:36 UTC
Labels: done
