### ISSUE TITLE
[Feature Request] Ability to filter or search the "File Tree"

### ISSUE THREAD

**Issue by morgwn** [ForkIssues/Tracker#959] opened 2020-04-04 06:51 UTC
It would be great to be able to filter (or search) the File Tree to narrow down on files and then be able to run a "history", etc on them. I'm interested in filenames, and optionally directories.

Similar to:  [[Feature request] Ability to filter branches in the graph #614](https://github.com/ForkIssues/Tracker/issues/614)

**Comment by CodingMarkus** [comment] 2020-04-06 16:49
Dupe of #428

**Closed as completed** 2020-04-06 16:54 UTC
